apiVersion: v1
kind: ConfigMap
metadata:
  name: healthchecks-config
data:
  DEBUG: "False"
  ADMINS: "admin.user@domain.com"   
  ALLOWED_HOSTS: ping.domain.com
  PING_ENDPOINT: "https://ping.domain.com/ping/"
  PING_BODY_LIMIT: "10000"
  SITE_NAME: "Notify"
  MASTER_BADGE_LABEL: "Notify"
  SITE_ROOT: https://ping.domain.com
  REMOTE_USER_HEADER: "HTTP_X_FORWARDED_EMAIL"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauthproxy-config
data:
  OAUTH2_PROXY_CLIENT_ID: healthchecks
  OAUTH2_PROXY_CLIENT_SECRET: qwertyuiopasdfghjklzxcvbbnm
  OAUTH2_PROXY_COOKIE_SECRET: random-base64-encoded-secret-see-oauth2-proxy-config=
  OAUTH2_PROXY_COOKIE_REFRESH: 4h
  OAUTH2_PROXY_COOKIE_SECURE: "false"
  OAUTH2_PROXY_COOKIE_HTTPONLY: "true"
  OAUTH2_PROXY_COOKIE_NAME: oauth2_proxy
  OAUTH2_PROXY_EMAIL_DOMAINS: "*"
  OAUTH2_PROXY_PROVIDER: keycloak
  OAUTH2_PROXY_REDIRECT_URL: https://ping.domain.com/oauth2/callback
  OAUTH2_PROXY_LOGIN_URL: https://keycloak.domain.com/realms/master/protocol/openid-connect/auth
  OAUTH2_PROXY_REDEEM_URL: https://keycloak.domain.com/realms/master/protocol/openid-connect/token
  OAUTH2_PROXY_PROFILE_URL: https://keycloak.domain.com/realms/master/protocol/openid-connect/userinfo
  OAUTH2_PROXY_VALIDATE_URL: https://keycloak.domain.com/realms/master/protocol/openid-connect/userinfo
